### PR TITLE
Fix issue 5510 / weeksToDays

### LINKED ISSUE #5510: Convert weeks to days
### Description

Write a program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```

### Tracking Issues

- [x] #5511
- [x] #5512
- [x] #5513
- [x] #5514
- [x] #5515
- [x] #5516
- [x] #5517
- [x] #5518
- [x] #5519
- [x] #5520
- [x] #5521
- [x] #5522
- [x] #5523
- [x] #5524
- [x] #5525
- [x] #5526
- [x] #5527
- [x] #5528
- [x] #5529
- [x] #5530

### LINKED ISSUE #5519: Write a JavaScript program to convert weeks to days
### Description

Write a JavaScript program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertWeeksToDays.js` file
- Add `ConvertWeeksToDays.js` file in `program/convert-weeks-to-days` folder

</details>

### PR DESCRIPTION
**Pull request by SarthakSanjay**
### Why:

Closes codinasion/codinasion#4167 

### What's being changed:
convert weeksToDays in js

### CODE REVIEW

**Review by anandfresh — CHANGES_REQUESTED** [review]
can you pls add the correct issue id ?

File: program/convert-weeks-to-days/ConvertWeeksToDays.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+let weeks = 5;
+let day = weeks * 7;
+
```
Comment (anandfresh) [inline program/convert-weeks-to-days/ConvertWeeksToDays.js:3]: can you change the variable name to 'days' , so that it will be appropriate

**Review by anandfresh — CHANGES_REQUESTED** [review]

File: program/convert-weeks-to-days/ConvertWeeksToDays.js (hunk 1 above)
Comment (SarthakSanjay) [reply program/convert-weeks-to-days/ConvertWeeksToDays.js:3]: ok

**Review by anandfresh — APPROVED** [review]
